version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - echo "Installing Terraform..."
      - wget https://releases.hashicorp.com/terraform/1.5.7/terraform_1.5.7_linux_amd64.zip
      - unzip terraform_1.5.7_linux_amd64.zip
      - mv terraform /usr/local/bin/
      - terraform --version

  build:
    commands:
      - echo "Initializing Terraform..."
      - cd cicd
      - terraform init --backend-config=config/dev.hcl
      - echo "Applying Terraform configuration..."
      - terraform apply --var-file=config/dev.tfvars -auto-approve

artifacts:
  files:
    - '**/*'
  discard-paths: yes